spring:
  application:
    name: EAProject
  datasource:
    url: jdbc:mysql://localhost:3306/cs544-project?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    serialization:
      fail-on-empty-beans: false
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
#  kafka:
#    consumer:
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      properties:
#        spring:
#          json:
#            trusted:
#              packages: bank.integration.kafka.message, kafka.message
logging:
  level:
    root: info
    org:
      springframework: info

app:
  queues:
    tax-service: taxQueue

